# Generated by Django 4.0.3 on 2022-10-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_bin',
        ),
        migrations.DeleteModel(
            name='BinVO',
        ),
    ]
